### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#212]
Enable automatically alerting people of new or modified content. 
This might require registration. 
We have a work around in place via the weekly NCELP digest.

Added note: being notified of every upload is probably too much and might put people off. Could we
- trigger an alert when a certain number (say 10) of new uploads has been reached
or
- have a timed (say weekly or monthly) alert which has all new content for a specific period

SP has previously suggested using RSS for alerts.

**Comment by WendyEBurns** [comment]
We now have a weekly bulletin established to alert people to new content (and we want people to sign up to this). Therefore these notifications would be for the NCELP team so that we don't have to manually copy and paste links and info from the 'modified by' list every week. The notification would include: 

URL of individual file (word doc, pdf, ppt etc)
URL of the associated resource
date file uploaded
by who. 
If possible, but not essential, indicating if it is associated with a collection(s).

The report should run at the same time every Sunday evening so that we have it on Monday morning ready to send out the bulletin AND update our file list - links to Resource list report #288
